# Generated by Django 3.0.8 on 2020-08-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msuser',
            name='user',
            field=models.TextField(),
        ),
    ]
