# Generated by Django 3.0.8 on 2020-08-01 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_remove_post_cover'),
        ('App', '0002_auto_20200801_0638'),
    ]

    operations = [
    ]
